//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetromApp.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int Id_Postare { get; set; }
        public string Id_User { get; set; }
        public string Comentariu { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Postari Postari { get; set; }
    }
}
