//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetromApp.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joke
    {
        public int Id { get; set; }
        public string Titlu { get; set; }
        public string Gluma { get; set; }
        public Nullable<int> Voturi { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string IdUser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
